/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClinicFeedbackRouteImport } from './routes/clinic-feedback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTriageRouteImport } from './routes/_app.triage'
import { Route as AppShapingRouteImport } from './routes/_app.shaping'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppRetrosRouteImport } from './routes/_app.retros'
import { Route as AppOverridesRouteImport } from './routes/_app.overrides'
import { Route as AppLeadershipRouteImport } from './routes/_app.leadership'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppGoliveRouteImport } from './routes/_app.golive'
import { Route as AppDeliveryRouteImport } from './routes/_app.delivery'
import { Route as AppDecisionsRouteImport } from './routes/_app.decisions'
import { Route as AppCommsRouteImport } from './routes/_app.comms'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppHelpSlugRouteImport } from './routes/_app.help.$slug'

const ClinicFeedbackRoute = ClinicFeedbackRouteImport.update({
  id: '/clinic-feedback',
  path: '/clinic-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppShapingRoute = AppShapingRouteImport.update({
  id: '/shaping',
  path: '/shaping',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRetrosRoute = AppRetrosRouteImport.update({
  id: '/retros',
  path: '/retros',
  getParentRoute: () => AppRoute,
} as any)
const AppOverridesRoute = AppOverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadershipRoute = AppLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppGoliveRoute = AppGoliveRouteImport.update({
  id: '/golive',
  path: '/golive',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppCommsRoute = AppCommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpSlugRoute = AppHelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppHelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/clinic-feedback': typeof ClinicFeedbackRoute
  '/admin': typeof AppAdminRoute
  '/comms': typeof AppCommsRoute
  '/decisions': typeof AppDecisionsRoute
  '/delivery': typeof AppDeliveryRoute
  '/golive': typeof AppGoliveRoute
  '/health': typeof AppHealthRoute
  '/help': typeof AppHelpRouteWithChildren
  '/intake': typeof AppIntakeRoute
  '/leadership': typeof AppLeadershipRoute
  '/overrides': typeof AppOverridesRoute
  '/retros': typeof AppRetrosRoute
  '/review': typeof AppReviewRoute
  '/roadmap': typeof AppRoadmapRoute
  '/shaping': typeof AppShapingRoute
  '/triage': typeof AppTriageRoute
  '/help/$slug': typeof AppHelpSlugRoute
}
export interface FileRoutesByTo {
  '/clinic-feedback': typeof ClinicFeedbackRoute
  '/admin': typeof AppAdminRoute
  '/comms': typeof AppCommsRoute
  '/decisions': typeof AppDecisionsRoute
  '/delivery': typeof AppDeliveryRoute
  '/golive': typeof AppGoliveRoute
  '/health': typeof AppHealthRoute
  '/help': typeof AppHelpRouteWithChildren
  '/intake': typeof AppIntakeRoute
  '/leadership': typeof AppLeadershipRoute
  '/overrides': typeof AppOverridesRoute
  '/retros': typeof AppRetrosRoute
  '/review': typeof AppReviewRoute
  '/roadmap': typeof AppRoadmapRoute
  '/shaping': typeof AppShapingRoute
  '/triage': typeof AppTriageRoute
  '/': typeof AppIndexRoute
  '/help/$slug': typeof AppHelpSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/clinic-feedback': typeof ClinicFeedbackRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/comms': typeof AppCommsRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/delivery': typeof AppDeliveryRoute
  '/_app/golive': typeof AppGoliveRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/help': typeof AppHelpRouteWithChildren
  '/_app/intake': typeof AppIntakeRoute
  '/_app/leadership': typeof AppLeadershipRoute
  '/_app/overrides': typeof AppOverridesRoute
  '/_app/retros': typeof AppRetrosRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/shaping': typeof AppShapingRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/help/$slug': typeof AppHelpSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinic-feedback'
    | '/admin'
    | '/comms'
    | '/decisions'
    | '/delivery'
    | '/golive'
    | '/health'
    | '/help'
    | '/intake'
    | '/leadership'
    | '/overrides'
    | '/retros'
    | '/review'
    | '/roadmap'
    | '/shaping'
    | '/triage'
    | '/help/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clinic-feedback'
    | '/admin'
    | '/comms'
    | '/decisions'
    | '/delivery'
    | '/golive'
    | '/health'
    | '/help'
    | '/intake'
    | '/leadership'
    | '/overrides'
    | '/retros'
    | '/review'
    | '/roadmap'
    | '/shaping'
    | '/triage'
    | '/'
    | '/help/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/clinic-feedback'
    | '/_app/admin'
    | '/_app/comms'
    | '/_app/decisions'
    | '/_app/delivery'
    | '/_app/golive'
    | '/_app/health'
    | '/_app/help'
    | '/_app/intake'
    | '/_app/leadership'
    | '/_app/overrides'
    | '/_app/retros'
    | '/_app/review'
    | '/_app/roadmap'
    | '/_app/shaping'
    | '/_app/triage'
    | '/_app/'
    | '/_app/help/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ClinicFeedbackRoute: typeof ClinicFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clinic-feedback': {
      id: '/clinic-feedback'
      path: '/clinic-feedback'
      fullPath: '/clinic-feedback'
      preLoaderRoute: typeof ClinicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shaping': {
      id: '/_app/shaping'
      path: '/shaping'
      fullPath: '/shaping'
      preLoaderRoute: typeof AppShapingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retros': {
      id: '/_app/retros'
      path: '/retros'
      fullPath: '/retros'
      preLoaderRoute: typeof AppRetrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overrides': {
      id: '/_app/overrides'
      path: '/overrides'
      fullPath: '/overrides'
      preLoaderRoute: typeof AppOverridesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leadership': {
      id: '/_app/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof AppLeadershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/golive': {
      id: '/_app/golive'
      path: '/golive'
      fullPath: '/golive'
      preLoaderRoute: typeof AppGoliveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery': {
      id: '/_app/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comms': {
      id: '/_app/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof AppCommsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/$slug': {
      id: '/_app/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof AppHelpSlugRouteImport
      parentRoute: typeof AppHelpRoute
    }
  }
}

interface AppHelpRouteChildren {
  AppHelpSlugRoute: typeof AppHelpSlugRoute
}

const AppHelpRouteChildren: AppHelpRouteChildren = {
  AppHelpSlugRoute: AppHelpSlugRoute,
}

const AppHelpRouteWithChildren =
  AppHelpRoute._addFileChildren(AppHelpRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCommsRoute: typeof AppCommsRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppGoliveRoute: typeof AppGoliveRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHelpRoute: typeof AppHelpRouteWithChildren
  AppIntakeRoute: typeof AppIntakeRoute
  AppLeadershipRoute: typeof AppLeadershipRoute
  AppOverridesRoute: typeof AppOverridesRoute
  AppRetrosRoute: typeof AppRetrosRoute
  AppReviewRoute: typeof AppReviewRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppShapingRoute: typeof AppShapingRoute
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCommsRoute: AppCommsRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppGoliveRoute: AppGoliveRoute,
  AppHealthRoute: AppHealthRoute,
  AppHelpRoute: AppHelpRouteWithChildren,
  AppIntakeRoute: AppIntakeRoute,
  AppLeadershipRoute: AppLeadershipRoute,
  AppOverridesRoute: AppOverridesRoute,
  AppRetrosRoute: AppRetrosRoute,
  AppReviewRoute: AppReviewRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppShapingRoute: AppShapingRoute,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ClinicFeedbackRoute: ClinicFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
